# -*- coding: utf-8 -*-
"""GasFee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEOGBo6MweKOlm-3zgunTWi2DZbmeNms
"""
import tensorflow as tf
from tensorflow.keras.layers import *
from tensorflow.keras import Sequential, Input, Model

## make a whenever input ## test accuracy ## hide the model code ## make sure it is runnable.

csv_file = 'ETH_1H.csv'

import pandas as pd

df = pd.read_csv(csv_file)
df.head()

df['Index'] = df.index

df['High']

y = df['High'] -df['Low']
input_data = df[['Index', 'Volume']]
input_data.shape, y.shape

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

input_data = sc.fit_transform(input_data)

split_ratio = 0.2

x_train, x_test, y_train, y_test = train_test_split(input_data, y, test_size=split_ratio, shuffle=True)
x_train.shape,y_train.shape

def expand_zero(data):
  return tf.expand_dims(input_data, axis = 0)

x_train = expand_zero(x_train)
y_train = expand_zero(y_train)
x_test = expand_zero(x_test)
y_test = expand_zero(y_test)

model = Sequential([
                    LSTM(64, activation = 'tanh', return_sequences = True),
                    LSTM(32, activation = 'tanh'),
                    BatchNormalization(),
                    Dense(16, activation = 'relu'),
                    Dense(1)
])

model.compile(optimizer = 'adam', loss = 'mse')

history = model.fit(x_train, y_train, validation_data=(x_test,y_test), verbose = 1, batch_size = 16, shuffle = True, epochs = 5)

## plot mse

model_file = 'gas_model.h5'
model.save(model_file)

## make a streamlit app ## ultimately we want this on our website
## uredi, čim manj kode, logo na vrhu, čim več pojasnjevanja. 
